### ISSUE TITLE
Failed to activate the enhanced-package-list package

### ISSUE THREAD

**Issue by michaelaye** [postcasio/enhanced-package-list#8]
[Enter steps to reproduce below:]
1. Click on Install button after finding package.
2. ...

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [enhanced-package-list](https://github.com/postcasio/enhanced-package-list) package, v1.0.3
### Stack Trace

Failed to activate the enhanced-package-list package

```
At undefined is not a function

TypeError: undefined is not a function
  at Object.module.exports.activate (/Users/klay6683/.atom/packages/enhanced-package-list/lib/enhanced-package-list.coffee:35:18)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:240:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:221:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:165:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:213:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:452:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:362:29
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:53:16)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)

```
### Commands

```
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
autocomplete-python, v0.5.1
color-picker, v2.0.7
enhanced-package-list, v1.0.3
language-cython, v0.3.0
linter-pep8, v0.2.0
linter-python-pyflakes, v0.1.0
minimap, v4.10.1
remote-edit, v1.8.4
travis-ci-status, v0.15.1

# Dev
No dev packages
```

**Comment by johnbwoodruff** [comment]
:+1: Same problem with me.

**Comment by github-polymer-user** [comment]
mee too
kill the bill

**Comment by ghost** [comment]
Same issue as reported.

**Comment by Shtucer** [comment]
`atom.packages.onDidActivateAll` is deprecated. Just chage it to
`atom.packages.onDidActivateInitialPackages` and now I have another error: 

> The enhanced-package-list package is not compatible with Atom &gt;= 0.167.0 and has been disabled.

Now this issue related with #9

**Comment by Timemashine** [comment]
Same issue

**Comment by mdaliyan** [comment]
same here

**Comment by mkelley88** [comment]
Same here. Nothing's fixed?

[Enter steps to reproduce:]

1. Error after install

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Ubuntu 17.10
**Thrown From**: [enhanced-package-list](https://github.com/postcasio/enhanced-package-list) package 1.0.3


### Stack Trace

Failed to activate the enhanced-package-list package

```
At atom.packages.onDidActivateAll is not a function

TypeError: atom.packages.onDidActivateAll is not a function
    at Object.activate (/packages/enhanced-package-list/lib/enhanced-package-list.coffee:35:18)
    at Package.activateNow (/usr/share/atom/resources/app/src/package.js:230:33)
    at measure (/usr/share/atom/resources/app/src/package.js:206:33)
    at Package.measure (/usr/share/atom/resources/app/src/package.js:88:25)
    at activationPromise.Promise (/usr/share/atom/resources/app/src/package.js:200:20)
    at Package.activate (/usr/share/atom/resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:695:42)
    at /usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:535:35
    at exit (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/usr/share/atom/resources/app/src/buffered-process.js:338:17)
    at /usr/share/atom/resources/app/src/buffered-process.js:359:17
    at Socket.<anonymous> (/usr/share/atom/resources/app/src/buffered-process.js:220:15)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
```

### Commands

```
     -1:28.9.0 core:confirm (input.hidden-input)
  4x -1:24.4.0 core:move-left (input.hidden-input)
     -1:23.4.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
enhanced-package-list 1.0.3 
pymakr 1.2.7 
```
